### ISSUE TITLE
lein cljsbuild once gives error.

### ISSUE THREAD

**Issue by gzmask** [emezeske/lein-cljsbuild#205]
I got this error:

java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: java.lang.Character
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:541)
    at clojure.java.io$fn__8496$G__8491__8501.invoke(io.clj:35)
    at clojure.java.io$file.invoke(io.clj:413)
    at leiningen.core.classpath$normalize_path.invoke(classpath.clj:247)
    at leiningen.core.classpath$get_classpath$iter__2055__2059$fn__2060.invoke(classpath.clj:277)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:60)
    at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
    at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
    at clojure.lang.LazySeq.next(LazySeq.java:92)
    at clojure.lang.RT.next(RT.java:598)
    at clojure.core$next.invoke(core.clj:64)
    at clojure.string$join.invoke(string.clj:186)
    at leiningen.core.eval$classpath_arg.invoke(eval.clj:191)
    at leiningen.core.eval$shell_command.invoke(eval.clj:197)
    at leiningen.core.eval$fn__2654.invoke(eval.clj:211)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:283)
    at leiningen.cljsbuild$run_local_project.invoke(cljsbuild.clj:22)
    at leiningen.cljsbuild$run_compiler.invoke(cljsbuild.clj:54)
    at leiningen.cljsbuild$once.invoke(cljsbuild.clj:109)
    at leiningen.cljsbuild$cljsbuild.doInvoke(cljsbuild.clj:196)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.core.main$resolve_task$fn__2171.doInvoke(main.clj:149)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.core.main$apply_task.invoke(main.clj:189)
    at leiningen.core.main$_main$fn__2232.invoke(main.clj:253)
    at leiningen.core.main$_main.doInvoke(main.clj:243)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.main$main_opt.invoke(main.clj:335)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at clojure.lang.Var.invoke(Var.java:427)
    at clojure.lang.AFn.applyToHelper(AFn.java:172)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)

my project.clj:

(defproject richeverpos "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[lein-cljsbuild "0.3.2"]]
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/clojurescript "0.0-1806"]]
  :source-paths ["src/clj"]
  :cljsbuild{:builds [{:source-paths "src/cljs"
                       :compiler {:output-to "resources/public/app.js"
                                  :optimizations :whitespace
                                  :pretty-print true}}]})

**Comment by marcelocra** [comment]
I had a similar problem, but for some reason I had [["src"]] and it should be ["src"].
