### ISSUE TITLE
Using symbolic links in sources directory

### ISSUE THREAD

**Issue by tillda** [emezeske/lein-cljsbuild#388]
I get a weird Clj exception while running a simple `lein cljsbuild once dev`. I have a suspicion that somehow symlinked directories aren't resolved properly, but I have no proof that that is actually the cause. In my project directory I symlink `src/stackone` to `env/stackone` (`../env/stackone`).

Weird thing is that it shouldn't even see the directory `stackone-lein/env/stackone` since the symlinks should make it totally transparent as a part of `src`.

The underlying exception is `Exception in thread "main" java.lang.AssertionError: Assert failed: (or (file? x) (url? x) (string? x)),` to which I can't find a source :(.

Here is the full stacktrace:

```
Reloading Clojure file "/Users/michal/Projects/stackone-lein/env/stackone/bootstrap.clj" failed.
java.io.FileNotFoundException: Could not locate Users/michal/Projects/stackone-lein/env/stackone/bootstrap__init.class or Users/michal/Projects/stackone-lein/env/stackone/bootstrap.clj on classpath.
                 RT.java:449 clojure.lang.RT.load
                 RT.java:412 clojure.lang.RT.load
               core.clj:5864 clojure.core/load[fn]
               core.clj:5863 clojure.core/load
             RestFn.java:408 clojure.lang.RestFn.invoke
            compiler.clj:129 cljsbuild.compiler/reload-clojure[fn]
            compiler.clj:128 cljsbuild.compiler/reload-clojure
            compiler.clj:174 cljsbuild.compiler/run-compiler
form-init5088282166948753830.clj:1 user/eval3923[fn]
form-init5088282166948753830.clj:1 user/eval3923[fn]
             LazySeq.java:40 clojure.lang.LazySeq.sval
             LazySeq.java:49 clojure.lang.LazySeq.seq
                 RT.java:507 clojure.lang.RT.seq
                core.clj:135 clojure.core/seq
               core.clj:3010 clojure.core/dorun
               core.clj:3026 clojure.core/doall
form-init5088282166948753830.clj:1 user/eval3923
          Compiler.java:6792 clojure.lang.Compiler.eval
          Compiler.java:6782 clojure.lang.Compiler.eval
          Compiler.java:7237 clojure.lang.Compiler.load
          Compiler.java:7175 clojure.lang.Compiler.loadFile
                main.clj:275 clojure.main/load-script
                main.clj:280 clojure.main/init-opt
                main.clj:308 clojure.main/initialize
                main.clj:343 clojure.main/null-opt
                main.clj:421 clojure.main/main
             RestFn.java:421 clojure.lang.RestFn.invoke
                Var.java:383 clojure.lang.Var.invoke
                AFn.java:156 clojure.lang.AFn.applyToHelper
                Var.java:700 clojure.lang.Var.applyTo
                main.java:37 clojure.main.main
Reloading Clojure file "/Users/michal/Projects/stackone-lein/env/stackone/devserver.clj" failed.
java.io.FileNotFoundException: Could not locate Users/michal/Projects/stackone-lein/env/stackone/devserver__init.class or Users/michal/Projects/stackone-lein/env/stackone/devserver.clj on classpath.
                 RT.java:449 clojure.lang.RT.load
                 RT.java:412 clojure.lang.RT.load
               core.clj:5864 clojure.core/load[fn]
               core.clj:5863 clojure.core/load
             RestFn.java:408 clojure.lang.RestFn.invoke
            compiler.clj:129 cljsbuild.compiler/reload-clojure[fn]
            compiler.clj:128 cljsbuild.compiler/reload-clojure
            compiler.clj:174 cljsbuild.compiler/run-compiler
form-init5088282166948753830.clj:1 user/eval3923[fn]
form-init5088282166948753830.clj:1 user/eval3923[fn]
             LazySeq.java:40 clojure.lang.LazySeq.sval
             LazySeq.java:49 clojure.lang.LazySeq.seq
                 RT.java:507 clojure.lang.RT.seq
                core.clj:135 clojure.core/seq
               core.clj:3010 clojure.core/dorun
               core.clj:3026 clojure.core/doall
form-init5088282166948753830.clj:1 user/eval3923
          Compiler.java:6792 clojure.lang.Compiler.eval
          Compiler.java:6782 clojure.lang.Compiler.eval
          Compiler.java:7237 clojure.lang.Compiler.load
          Compiler.java:7175 clojure.lang.Compiler.loadFile
                main.clj:275 clojure.main/load-script
                main.clj:280 clojure.main/init-opt
                main.clj:308 clojure.main/initialize
                main.clj:343 clojure.main/null-opt
                main.clj:421 clojure.main/main
             RestFn.java:421 clojure.lang.RestFn.invoke
                Var.java:383 clojure.lang.Var.invoke
                AFn.java:156 clojure.lang.AFn.applyToHelper
                Var.java:700 clojure.lang.Var.applyTo
                main.java:37 clojure.main.main
Compiling "resources/public/lein-cljsbuild-dev/app-dev.js" from ["src"]...
Compiling "resources/public/lein-cljsbuild-dev/app-dev.js" failed.
Exception in thread "main" java.lang.AssertionError: Assert failed: (or (file? x) (url? x) (string? x)), compiling:(/private/var/folders/ym/l2qxd7l97kzfzftrdpqsclm40000gn/T/form-init5088282166948753830.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7249)
	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: (or (file? x) (url? x) (string? x))
	at cljs.util$ext.invoke(util.clj:114)
	at cljs.closure$source_on_disk.invoke(closure.clj:1172)
	at cljs.closure$output_unoptimized$fn__3624.invoke(closure.clj:1201)
	at clojure.core$map$fn__4531.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4106.invoke(core.clj:135)
	at clojure.core$filter$fn__4558.invoke(core.clj:2677)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4106.invoke(core.clj:135)
	at clojure.core$map$fn__4531.invoke(core.clj:2614)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:674)
	at clojure.core$next__4090.invoke(core.clj:64)
	at clojure.core$str$fn__4166.invoke(core.clj:528)
	at clojure.core$str.doInvoke(core.clj:526)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:628)
	at cljs.closure$deps_file.invoke(closure.clj:1015)
	at cljs.closure$output_deps_file.invoke(closure.clj:1035)
	at cljs.closure$output_unoptimized.doInvoke(closure.clj:1215)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:630)
	at cljs.closure$build.invoke(closure.clj:1480)
	at cljs.closure$build.invoke(closure.clj:1392)
	at cljsbuild.compiler$compile_cljs$fn__3791.invoke(compiler.clj:81)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:80)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:180)
	at user$eval3923$iter__3959__3963$fn__3964$fn__3982.invoke(form-init5088282166948753830.clj:1)
	at user$eval3923$iter__3959__3963$fn__3964.invoke(form-init5088282166948753830.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4106.invoke(core.clj:135)
	at clojure.core$dorun.invoke(core.clj:3010)
	at clojure.core$doall.invoke(core.clj:3026)
	at user$eval3923.invoke(form-init5088282166948753830.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6792)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	... 11 more 
```

**Comment by tillda** [comment]
It happened to be caused by a different thing :).

**Comment by astoeckley** [comment]
I'm curious what was causing your `java.io.FileNotFoundException` because I am having this identical issue with a symblink. However, my compiled js is fine, the cljsbuild does complete without issue, but it spits out this exception with a stack trace anyway, and I wonder why and if there is anything I can do about it?
