### ISSUE TITLE
warning-handlers being called with wrong arity

### ISSUE THREAD

**Issue by mattly** [emezeske/lein-cljsbuild#403]
I'm attempting to make cljsbuild stop the lein process during our uberjar build when a SEVERE error is encountered and trying to make sense of the `warning-handlers` option. I copied and pasted the example print function from the Readme into my project.clj as such:

``` clj
             :uberjar {:source-paths ["env/prod/clj"]
                       :hooks [leiningen.cljsbuild]
                       :env {:production true}
                       :omit-source true
                       :aot :all
                       :cljsbuild {:builds {:app {:source-paths ["env/prod/cljs"]
                                                  :compiler {:optimizations :advanced
                                                             :pretty-print false
                                                             :source-map false}
                                                  :warning-handlers [(fn [warning-type env extra]
                                                                       (when-let [s (cljs.analyzer/error-message warning-type extra)]
                                                                         (binding [*out* *err*]
                                                                           (cljs.analyzer/message env s))))
                                                                     ]}}}}})
```

and when building the uberjar I get this error:

```
Compiling ClojureScript.
clojure.lang.ArityException: Wrong number of args (1) passed to: user/eval4126/fn--4127
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at user$eval4126.invoke(form-init4125560282857407600.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at user$eval4016$iter__4052__4056$fn__4057.invoke(form-init4125560282857407600.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$dorun.invoke(core.clj:3009)
	at clojure.core$doall.invoke(core.clj:3025)
	at user$eval4016.invoke(form-init4125560282857407600.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Uberjar aborting because jar failed: Subprocess failed
```

It has the desired effect... while also breaking on regular warnings of the sort emitted by a handful of libraries we're using.

Any ideas? Alternately, are there any examples of how to halt the build like this?

**Comment by cemerick** [comment]
Maybe @sgrove can pipe in on this. The usage looks okay to me, but I'm not in a position to validate it at the moment.

**Comment by mneise** [comment]
@mattly Wasn't able to reproduce this issue. Are you still having problems with this? If yes, could you please provide a minimal repo?

**Comment by mattly** [comment]
I'm no longer working on the project where this was an issue, and my current project uses boot instead of lein. I can take a stab at this sometime but chances are I won't be able to reproduce it either.
