### ISSUE TITLE
"No such namespace: lists.lib, could not locate lists/lib.cljs, lists/lib.cljc, or Closure namespace "lists.lib" {:tag :cljs/analysis-error}"

### ISSUE THREAD

**Issue by brhs** [emezeske/lein-cljsbuild#433]
(My project is called `lists`.)

Here's my `project.clj`:

    (defproject lists "0.0.1"
      :dependencies [[org.clojure/clojure "1.7.0"]
                    [org.clojure/clojurescript "1.7.170"]]
      :cljsbuild {:builds [{:source-paths ["src/cljs"]
                            :compiler {:optimizations :simple
                                       :main lists.core
                                       :output-to "lists.js"
                                       :target :nodejs}}]}
      :source-paths ["src/clj"]
      :plugins [[lein-cljsbuild "1.1.2"]])

src/cljs/lists/core.cljs:

    (ns lists.core
      (:require [lists.lib :as lib :include-macros true]))

    (lib/defmain [& args]
      (.log js/console "hello world"))

src/clj/lists/lib.clj:

    (ns lists.lib)

    (defmacro defmain [& body]
      `(set! *main-cli-fn* (fn ~@body)))

When I run `lein cljsbuild once`, this shows up:

    Compiling ClojureScript...
    Compiling "lists.js" from ["src/cljs"]...
    Compiling "lists.js" failed.
    clojure.lang.ExceptionInfo: failed compiling file:/Users/bh/code/lists/src/cljs/lists/core.cljs {:file #object[java.io.File 0x1ea6446b "/Users/bh/code/lists/src/cljs/lists/core.cljs"]}
      at clojure.core$ex_info.invoke(core.clj:4593)
      at cljs.compiler$compile_file$fn__3236.invoke(compiler.cljc:1343)
      at cljs.compiler$compile_file.invoke(compiler.cljc:1310)
      at cljs.closure$compile_file.invoke(closure.clj:434)
      at cljs.closure$eval3638$fn__3639.invoke(closure.clj:491)
      at cljs.closure$eval3577$fn__3578$G__3566__3585.invoke(closure.clj:391)
      at cljs.closure$compile_sources$iter__3741__3745$fn__3746.invoke(closure.clj:755)
      at clojure.lang.LazySeq.sval(LazySeq.java:40)
      at clojure.lang.LazySeq.seq(LazySeq.java:49)
      at clojure.lang.Cons.next(Cons.java:39)
      at clojure.lang.RT.next(RT.java:674)
      at clojure.core$next__4112.invoke(core.clj:64)
      at clojure.core$dorun.invoke(core.clj:3010)
      at clojure.core$doall.invoke(core.clj:3025)
      at cljs.closure$compile_sources.invoke(closure.clj:751)
      at cljs.closure$build.invoke(closure.clj:1807)
      at cljs.build.api$build.invoke(api.clj:207)
      at cljs.build.api$build.invoke(api.clj:201)
      at cljsbuild.compiler$compile_cljs$fn__4227.invoke(compiler.clj:60)
      at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:59)
      at cljsbuild.compiler$run_compiler.invoke(compiler.clj:168)
      at user$eval4364$iter__4400__4404$fn__4405$fn__4423.invoke(form-init5354891691359765820.clj:1)
      at user$eval4364$iter__4400__4404$fn__4405.invoke(form-init5354891691359765820.clj:1)
      at clojure.lang.LazySeq.sval(LazySeq.java:40)
      at clojure.lang.LazySeq.seq(LazySeq.java:49)
      at clojure.lang.RT.seq(RT.java:507)
      at clojure.core$seq__4128.invoke(core.clj:137)
      at clojure.core$dorun.invoke(core.clj:3009)
      at clojure.core$doall.invoke(core.clj:3025)
      at user$eval4364.invoke(form-init5354891691359765820.clj:1)
      at clojure.lang.Compiler.eval(Compiler.java:6782)
      at clojure.lang.Compiler.eval(Compiler.java:6772)
      at clojure.lang.Compiler.load(Compiler.java:7227)
      at clojure.lang.Compiler.loadFile(Compiler.java:7165)
      at clojure.main$load_script.invoke(main.clj:275)
      at clojure.main$init_opt.invoke(main.clj:280)
      at clojure.main$initialize.invoke(main.clj:308)
      at clojure.main$null_opt.invoke(main.clj:343)
      at clojure.main$main.doInvoke(main.clj:421)
      at clojure.lang.RestFn.invoke(RestFn.java:421)
      at clojure.lang.Var.invoke(Var.java:383)
      at clojure.lang.AFn.applyToHelper(AFn.java:156)
      at clojure.lang.Var.applyTo(Var.java:700)
      at clojure.main.main(main.java:37)
    Caused by: clojure.lang.ExceptionInfo: No such namespace: lists.lib, could not locate lists/lib.cljs, lists/lib.cljc, or Closure namespace "lists.lib" {:tag :cljs/analysis-error}
      at clojure.core$ex_info.invoke(core.clj:4593)
      at cljs.analyzer$error.invoke(analyzer.cljc:568)
      at cljs.analyzer$error.invoke(analyzer.cljc:566)
      at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1656)
      at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2492)
      at cljs.analyzer$analyze_STAR_$fn__1990.invoke(analyzer.cljc:2573)
      at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
      at clojure.core$reduce.invoke(core.clj:6518)
      at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2573)
      at cljs.analyzer$analyze.invoke(analyzer.cljc:2588)
      at cljs.compiler$compile_file_STAR_$fn__3196.invoke(compiler.cljc:1221)
      at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1149)
      at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1172)
      at cljs.compiler$compile_file$fn__3236.invoke(compiler.cljc:1331)
      ... 42 more
    Subprocess failed

Any ideas?

**Comment by mneise** [comment]
The way macros are included in ClojureScript differs from Clojure (https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure#macros). To include a macro from a `clj` file, you need to use `:require-macros`, for example:

```clojure
(ns lists.core
  (:require-macros [lists.lib :as lib]))

(lib/defmain [& args]
  (.log js/console "hello world"))
```

**Comment by danielcompton** [comment]
Expanding on @mneise comment, the reason why `:include-macros` doesn't work here is that it expands out into a `:require` and a `:require-macros`. The require-macros looks for a clj file and finds it, but the require looks for a cljs or cljc file and cannot find it, leading to the error.
