### ISSUE TITLE
Fails on Java 9?

### ISSUE THREAD

**Issue by rnikander** [emezeske/lein-cljsbuild#483]
Is lein-cljsbuild supposed to work on Java 9? It works fine on Java 8, but if I use Java 9 I get the error below.  (I'm on macOS.)

    $ lein cljsbuild once
    Compiling ClojureScript...
    Compiling 17 source files to /Users/rob/.../target/default/classes
    Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
       at clojure.lang.Compiler.load(Compiler.java:7526)
       at clojure.lang.RT.loadResourceScript(RT.java:379)
       at clojure.lang.RT.loadResourceScript(RT.java:370)
       at clojure.lang.RT.load(RT.java:460)
       at clojure.lang.RT.load(RT.java:426)

**Comment by danielcompton** [comment]
Hi @rnikander there are a few things you need to do to get ClojureScript projects working with Java 9, this isn't a cljsbuild bug. See https://www.deps.co/blog/how-to-upgrade-your-clojure-projects-to-use-java-9/ for more details.

**Comment by rnikander** [comment]
Thank you for the info. Closing.
